# Generated by Django 4.2.4 on 2023-08-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=50, unique=True, verbose_name='Todo title')),
                ('body', models.TextField(help_text='Write about details of your to-do', verbose_name='Post body')),
            ],
        ),
    ]
