# Generated by Django 4.2.4 on 2023-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Completed',
            field=models.BooleanField(choices=[(True, 'Completed'), (False, 'Not Completed')], default=False, help_text='If you complete,then click', verbose_name='Is it Completed?'),
        ),
    ]
